import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={`${styles.container} ${styles.home}`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet' />

      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>

          <Link href="/CssUtility" >
            <a className={styles.card}>
              <h3>Css Utility   &rarr;</h3>
              <p>Transform your Raw Css to Variable based CSS.</p>
            </a>
          </Link>
        </div>
        <script>

        </script>

      </main>

    </div>
  )
}

export default Home
