import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import CssTransform from './CssUtility'

const Home: NextPage = () => {
  return (
    <div className={`${styles.container} ${styles.home}`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet' />

      </Head>

      <main className={styles.main}>
        <CssTransform />
      </main>

    </div>
  )
}

export default Home
